spring.application.name=GeminiAi
spring.ai.google.genai.api-key=${GEMINI_AI_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-pro-preview
#spring.ai.google.genai.chat.options.response-mime-type=application/json
spring.ai.google.genai.chat.options.google-search-retrieval=true
tool.last.changes.days=30

# Logging Configuration
# Log file location and name
logging.file.name=logs/application.log

# Log level for the application
logging.level.org.ai.gemini.geminiai=DEBUG

app.ai.batch-size=10
app.ai.timeout.individual=180
app.ai.timeout.batch=300