spring.application.name=GeminiAi
spring.ai.google.genai.api-key=${GEMINI_AI_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.8-flash
spring.ai.google.genai.chat.options.google-search-retrieval=true
tool.last.changes.days=30

# Logging Configuration
logging.file.name=logs/application.log
logging.level.org.ai.gemini.geminiai=DEBUG

app.ai.batch-size=10
app.ai.timeout.individual=180
app.ai.timeout.batch=300
