spring.application.name=GeminiAi
spring.ai.google.genai.api-key=${GEMINI_AI_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-pro-preview
#spring.ai.google.genai.chat.options.response-mime-type=application/json
spring.ai.google.genai.chat.options.google-search-retrieval=true